services:
  - type: web
    name: mf-bot-1am
    env: docker
    plan: free
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false  # ใส่ค่าจริงใน Dashboard
      - key: GUILD_ID
        sync: false
      - key: VC_CHANNEL_ID
        sync: false
      - key: TEXT_CHANNEL_ID
        sync: false
      - key: ENABLE_VOICE
        value: "0"
